# Netlify configuration for Kamunity - ROOT LEVEL CONFIG

[build]
  # Build command - ensure all dependencies including devDependencies are installed
  command = "npm ci --include=dev && npm run build"
  
  # Publish directory for Next.js
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://kamunity.org"
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NODE_ENV = "production"
  
  # Default email settings - these will be overridden by environment variables in Netlify dashboard
  RESEND_FROM_EMAIL = "hello@kamunity.org"
  MIKE_FULLER_EMAIL = "mike@kamunityconsulting.com"
  NEXT_PUBLIC_CRISP_WEBSITE_ID = "placeholder_id"

# NOTE: Email API key should be set in Netlify dashboard environment variables:
# - RESEND_API_KEY (your Resend API key for email functionality)

# Netlify will auto-detect Next.js and handle API routes automatically

# Headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 